import { Supernova, PulsarContext, RemoteVersionIdentifier, AnyOutputFile, Token, TokenGroup, TokenType } from "@supernovaio/sdk-exporters"
import { ExporterConfiguration } from "../config"
import { FileHelper } from "@supernovaio/export-helpers"
import { convertToken, tokenName, tokenTypeName, TokenJsonEntry, TypographyAtomicEntries } from "./content/tokenConverter"

Pulsar.export(async (sdk: Supernova, context: PulsarContext): Promise<Array<AnyOutputFile>> => {
  const remoteVersionIdentifier: RemoteVersionIdentifier = {
    designSystemId: context.dsId,
    versionId: context.versionId,
  }

  let tokens = await sdk.tokens.getTokens(remoteVersionIdentifier)
  let tokenGroups = await sdk.tokens.getTokenGroups(remoteVersionIdentifier)

  if (context.brandId) {
    const brands = await sdk.brands.getBrands(remoteVersionIdentifier)
    const brand = brands.find((b) => b.id === context.brandId || b.idInVersion === context.brandId)
    if (!brand) {
      throw new Error(`Unable to find brand ${context.brandId}.`)
    }
    tokens = tokens.filter((t) => t.brandId === brand.id)
    tokenGroups = tokenGroups.filter((tg) => tg.brandId === brand.id)
  }

  if (context.themeIds && context.themeIds.length > 0) {
    const themes = await sdk.tokens.getTokenThemes(remoteVersionIdentifier)
    const themesToApply = context.themeIds.map((themeId) => {
      const theme = themes.find((t) => t.id === themeId || t.idInVersion === themeId)
      if (!theme) {
        throw new Error(`Unable to find theme ${themeId}.`)
      }
      return theme
    })
    tokens = sdk.tokens.computeTokensByApplyingThemes(tokens, tokens, themesToApply)
  }

  const tokensByType = groupTokensByType(tokens)

  if (exportConfiguration.splitByTokenType) {
    return buildMultiFileOutput(tokensByType, tokenGroups)
  }
  return buildSingleFileOutput(tokensByType, tokenGroups)
})

export const exportConfiguration = Pulsar.exportConfig<ExporterConfiguration>()

function groupTokensByType(tokens: Array<Token>): Map<TokenType, Array<Token>> {
  const map = new Map<TokenType, Array<Token>>()
  for (const token of tokens) {
    const list = map.get(token.tokenType) ?? []
    list.push(token)
    map.set(token.tokenType, list)
  }
  return map
}

function isAtomicResult(value: any): value is TypographyAtomicEntries {
  return value && typeof value === "object" && value.kind === "atomic"
}

function buildTokenEntries(
  tokens: Array<Token>,
  tokenGroups: Array<TokenGroup>
): Record<string, TokenJsonEntry> {
  const result: Record<string, TokenJsonEntry> = {}
  for (const token of tokens) {
    const name = tokenName(token, tokenGroups, exportConfiguration)
    const converted = convertToken(token, exportConfiguration)
    if (converted === null) continue

    if (isAtomicResult(converted)) {
      for (const [suffix, sub] of Object.entries(converted.entries)) {
        const atomicKey = `${name}${suffix.charAt(0).toUpperCase()}${suffix.slice(1)}`
        const entry: TokenJsonEntry = { value: sub.value, type: sub.type }
        if (exportConfiguration.includeDescriptions && token.description) {
          entry.description = token.description
        }
        result[atomicKey] = entry
      }
    } else {
      const entry: TokenJsonEntry = {
        value: converted,
        type: tokenTypeName(token.tokenType),
      }
      if (exportConfiguration.includeDescriptions && token.description) {
        entry.description = token.description
      }
      result[name] = entry
    }
  }
  return result
}

function buildSingleFileOutput(
  tokensByType: Map<TokenType, Array<Token>>,
  tokenGroups: Array<TokenGroup>
): Array<AnyOutputFile> {
  const output: Record<string, Record<string, TokenJsonEntry>> = {}

  for (const [type, tokens] of tokensByType) {
    const typeName = tokenTypeName(type)
    const entries = buildTokenEntries(tokens, tokenGroups)
    if (Object.keys(entries).length > 0) {
      output[typeName] = entries
    }
  }

  let json: any = output
  if (exportConfiguration.generateDisclaimer) {
    json = { _comment: "This file was generated by Supernova, don't change by hand", ...output }
  }

  return [
    FileHelper.createTextFile({
      relativePath: "./",
      fileName: "tokens.json",
      content: JSON.stringify(json, null, 2),
    }),
  ]
}

function buildMultiFileOutput(
  tokensByType: Map<TokenType, Array<Token>>,
  tokenGroups: Array<TokenGroup>
): Array<AnyOutputFile> {
  const files: Array<AnyOutputFile> = []

  for (const [type, tokens] of tokensByType) {
    const typeName = tokenTypeName(type)
    const entries = buildTokenEntries(tokens, tokenGroups)
    if (Object.keys(entries).length === 0) continue

    let json: any = entries
    if (exportConfiguration.generateDisclaimer) {
      json = { _comment: "This file was generated by Supernova, don't change by hand", ...entries }
    }

    files.push(
      FileHelper.createTextFile({
        relativePath: "./",
        fileName: `${typeName}.json`,
        content: JSON.stringify(json, null, 2),
      })
    )
  }

  return files
}
